voca/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^', include('word.urls', namespace='word')),
]

word/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^list/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$', views.list, name='list'),
	url(r'^check/(?P<id>[0-9]+)/$', views.check, name="check"),
	url(r'^done/(?P<id>[0-9]+)/$', views.done, name="done"),
	url(r'^new/$', views.new, name="new"),
	url(r'^create/$', views.create, name="create"),
	url(r'^download_voice/(?P<id>[0-9]+)/$', views.downloadVoice, name="downloadVoice"),
]

word/models.py
from django.db import models
# from datetime import date, datetime, time
# from django.utils import timezone
from django.conf import settings

from datetime import datetime, timedelta
from pytz import timezone
import django.utils
import pytz
import os

from .downloader import download

MEMORY_CURVE_C = settings.MEMORY_CURVE_C
MEMORY_CURVE_END = settings.MEMORY_CURVE_END

class Word(models.Model):
	code = models.CharField(max_length=50, unique=True)
	word = models.CharField(max_length=50)
	pronounce_url = models.TextField()
	pronounce = models.CharField(max_length=50)
	explainatin = models.TextField()
	example = models.TextField()

	next_review_at = models.DateTimeField(default=django.utils.timezone.now)
	graduated = models.BooleanField(default=False)

	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def calculate_next_review_date(self):
		_c = self.review_set.count()
		delta = MEMORY_CURVE_C * _c * _c
		if delta <= MEMORY_CURVE_END + 1:
			start = self.review_set.order_by('-created_at').first().created_at
			self.next_review_at = start + timedelta(days=delta)
			return self.save()
		else:
			return None

	def downloadPronounceFile(self):
		download(self.pronounce_url, os.path.join("word", self.code + ".mp3"))

	def getDateTuple(self):
		return (self.next_review_at.year, self.next_review_at.month, self.next_review_at.day)

	def __str__(self):
		return self.word

class Review(models.Model):
	word = models.ForeignKey(Word, on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.word.word + ' at '+ str(self.created_at)

word/forms.py
from django.forms import ModelForm
from word.models import Word

class AddWordForm(ModelForm):
	class Meta:
		model = Word
		fields = ['word', 'pronounce', 'pronounce_url', 'explainatin', 'example']

word/views.py
from django.db.models import Count
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.conf import settings

from datetime import datetime, timedelta
from pytz import timezone
import pytz
import os

from .forms import AddWordForm
from .models import Word

SETTING_TIME_ZONE = timezone(settings.TIME_ZONE)

def _get_next_day_midnight():
	now = datetime.now()
	midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
	midnight = SETTING_TIME_ZONE.localize(midnight) + timedelta(days=1)
	return midnight

def _get_next_midnight(year, month, day):
	now = datetime.now()
	midnight = now.replace(year=year, month=month, day=day, hour=0, minute=0, second=0, microsecond=0)
	midnight = SETTING_TIME_ZONE.localize(midnight) + timedelta(days=1)
	return midnight

def _get_midnight(year, month, day):
	now = datetime.now()
	midnight = now.replace(year=year, month=month, day=day, hour=0, minute=0, second=0, microsecond=0)
	midnight = SETTING_TIME_ZONE.localize(midnight)
	return midnight


def index(request):
	midnight = _get_next_day_midnight()

	counts = Word.objects.filter(graduated=False).extra({'next_review_date' : 'date(next_review_at)'})\
					.values('next_review_date').annotate(count=Count('id'))\
					.order_by('next_review_date')

	onProgress = Word.objects.filter(graduated=False).count()
	graduates = Word.objects.filter(graduated=True).count()

	return render(request, 'word/index.html', {'counts': counts, 
											'onProgress': onProgress, 
											'graduates': graduates,
											'midnight': midnight,})

def list(request, year, month, day):
	year = int(year)
	month = int(month)
	day = int(day)
	midnight = _get_midnight(year, month, day)
	next_midnight = _get_next_midnight(year, month, day)

	word_list = Word.objects.filter(graduated=False)\
				.filter(next_review_at__gte=midnight)\
				.filter(next_review_at__lt=next_midnight)\
				.annotate(rc=Count('review'))\
				.order_by('-created_at')
	total = word_list.count()

	return render(request, 'word/list.html', 
					{'word_list': word_list,
					'total': total,})

def check(request, id):
	word = Word.objects.get(pk=id)
	year, month, day = word.getDateTuple()

	return render(request, 'word/check.html', 
							{'word': word, 'year': year, 'month': month, 'day': day})

def done(request, id):
	word = Word.objects.get(pk=id)

	if word.next_review_at > _get_next_day_midnight():
		return HttpResponse("The review date has not reached.")
	else:
		year, month, day = word.getDateTuple()
		word.review_set.create()
		word.calculate_next_review_date()
		return redirect(reverse('word:list', kwargs={'year': year, 'month': month, 'day': day}))

def new(request):
	form = AddWordForm()
	return render(request, 'word/new.html', {'form': form})

def create(request):
	f = AddWordForm(request.POST)
	if f.is_valid():
		e = f.save()
	return redirect(reverse('word:list'))

def downloadVoice(request, id):
	word = Word.objects.get(pk=id)
	word.downloadPronounceFile()
	return redirect(reverse('word:list'))

word/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Voca System</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    {% block head_static %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div id="page_container" class="container">

    {% block body %}{% endblock %}
    </div>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

  </body>
</html>

word/templates/word/check.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body %}

<div id="word_check_page">

<h1>{{ word.word }}</h1>

<p>/{{ word.pronounce }}/</p>


<div class="row">

	<div class="col-md-8">
		<h2>{{ word.explainatin }}</h2>
		<!-- audio controls class="pull-right">
			{% with 'word/'|add:word.code|add:'.mp3' as mp3_url %}
			<source src="{% static mp3_url %}" type="audio/mpeg">
			{% endwith %}
		</audio -->

		<h3>{{ word.example }}</h3>
	</div>
</div>

<form action="{% url 'word:done' word.id %}" method="POST">
	{% csrf_token %}
	<input type="submit" value="DONE WITH THE WORD" tabindex="1" class="btn btn-primary">
</form>

<a tabindex="2" href="{% url 'word:list' year month day %}" class="btn btn-default">Go Back</a>

</div>
{% endblock %}

word/templates/word/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body %}

<a href="{% url 'word:new' %}" class="btn btn-info">New Word</a>
<hr>
<table class="table">
{% for count in counts %}
	{% if count.next_review_date|date:"Y-m-d" < midnight|date:"Y-m-d" %}
	<tr class="warning">
	{% else %}
	<tr>
	{% endif %}

		<td class="col-sm-2">
			{{count.next_review_date}}
		</td>

		<td class="col-sm-1">
			{% if count.count > 50 %}
				<span class="label label-danger">{{count.count}}</span>
			{% else %}
				<span class="label label-default">{{count.count}}</span>
			{% endif %}
			
		</td>
		<td>
			{% if count.next_review_date|date:"Y-m-d" < midnight|date:"Y-m-d" %}
			<a class="btn btn-xs btn-default" 
				href="{% url 'word:list' count.next_review_date.year count.next_review_date.month count.next_review_date.day %}">Review</a>
			{% endif %}
		</td>
	</tr>
{% endfor %}
</table>
<i>Progress: {{onProgress}} / Graduates: {{graduates}}</i>
{% endblock %}

word/templates/word/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_static %}
	<link rel="stylesheet" type="text/css" href="{% static 'word/css/index.css' %}" />
{% endblock %}

{% block body %}

<div id="word_index_page">

<h1>Remain: {{ total }}</h1>

<a class="pull-right btn btn-default" href="{% url 'word:index' %}">Back</a>

<ul id="audio_list">
{% for w in word_list %}
	<li>
		<audio controls id="audio_{{w.id}}">
			{% with 'word/'|add:w.code|add:'.mp3' as mp3_url %}
			<source src="{% static mp3_url %}" type="audio/mpeg">
			{% endwith %}
		</audio>

		<form class="form-inline" action="{% url 'word:check' w.id %}">
			<div class="form-group">
				<input class="practice form-control" audio="audio_{{w.id}}" word="{{w.word}}" tabindex="{{forloop.counter}}">
			</div>

			<a href="{% url 'word:check' w.id %}" class="btn btn-primary">check</a>

			<a href="{% url 'word:downloadVoice' w.id %}" class="btn btn-default btn-xs">
				<i>download voice</i>
			</a>

			<span class="badge">{{w.rc}}</span>
		</form>
	</li>
{% endfor %}
</ul>

<script src="{% static 'word/js/index.js' %}"></script>

</div><!-- word_index_page -->
{% endblock %}

word/templates/word/new.html
<form action="{% url 'word:create' %}" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>